from typing import Any, Dict

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pathlib import Path
from fastapi.staticfiles import StaticFiles

from app.routes.ingestion import router as ingestion_router
from app.routes.engine import router as engine_router


app = FastAPI(
    title="FinForge Backend",
    description="Financial data ingestion and processing API",
    version="1.0.0",
)


app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


app.include_router(
    ingestion_router
)

app.include_router(
    engine_router
)

# Serve chart PNGs generated by deterministic engine
app.mount("/charts", StaticFiles(directory=Path(__file__).resolve().parents[2] / "deterministic_engine" / "result"), name="charts")


@app.get("/")
async def root() -> Dict[str, str]:

    return {
        "service": "FinForge Backend",
        "status": "running",
    }


@app.get("/health")
async def health() -> Dict[str, Any]:

    return {
        "status": "ok",
        "service": "finforge-backend",
    }


if __name__ == "__main__":

    import uvicorn

    uvicorn.run(
        "app.main:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
    )